---
title: Presentations
toc: true
---

## MESM Master’s Project Presentation: UCSB Bren School (2025)
- [DebrisEase Final Presentation (Slides)](https://docs.google.com/presentation/d/17jRBfrULD3nC80rSouRQYznrtJU87UXNadHZZkO6WAE/edit?usp=sharing)
- [2025 MESM Master's Project Presentations, Session A, starting at 3:05:00 (Video)](https://www.youtube.com/watch?v=c4nZVVFpJTY)

## Watershed Education: Creating a Video for Santa Barbara Channelkeeper (2025)
- [Watershed Education Video: in the making (Slides)](https://www.canva.com/design/DAGmywRQOkw/a2jlm7WBZkdhqP04Z28MRA/edit?utm_content=DAGmywRQOkw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

## Southern California Academy of Sciences (SCAS) 2023 Annual Meeting
- [SCAS_2023_Presentation (Video)](https://drive.google.com/file/d/1HVQQAWB9oZK2pphoO9dpMzRa1bDcge4i/view?usp=sharing)
- [SCAS Presentation 2023 (Slides)](https://docs.google.com/presentation/d/1HoegK-Zh1sFTXbotens42VURBC-X8ChJV0hkoV8cras/edit?usp=sharing)

## International Conference on Copepoda (e-ICOC) 2022 – Lightning Talk
- [e-ICOC 2022 - Nicothoid Project (Slides)](https://docs.google.com/presentation/d/1oCrAo2qbTVd2x6813EvGr-UbyZ4K4sJP3TbU3P0OCDc/edit?usp=drive_link)

## Disparities in Seafood Processing and Consumption (2025)
- [A literature review: disparities in seafood processing and consumption (Slides)](https://www.canva.com/design/DAGoG0BRkFc/dimLrJKIijW2AakpYQPuXA/edit?utm_content=DAGoG0BRkFc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

## Cost-Benefit Analysis Final Presentation (2025)
- [CBA_Final_Presentation_Lagunas_Lecuona (Slides)](https://docs.google.com/presentation/d/1RpLkmoMFg4P536SnVEpEUSTp-ix8pD6eNFMiahzGrEo/edit?usp=sharing)
- [Final Report CBA - Lagunas, Lecuona](https://docs.google.com/document/d/1HTejwp7NEcPvQraWzw4Tgs-JKDFHUvCrSUMMBQ5YwYI/edit?usp=drive_link)

## Disparities in Flood Vulnerability (2025)
- [Flood Vulnerability (Slides)](https://docs.google.com/presentation/d/1nBuvpgl7r_NiNYxWX2eBRTwjYV2JSr2LzSf7T03vnLs/edit?usp=sharing)

## Scoping Plastic Waste Streams at Music Festivals (2023)
- [Concerted Final Presentation (Slides)](https://docs.google.com/presentation/d/16SpfpbRcf1rQl1X835ZHCy7bHIby6meOS3_p__wm8DU/edit?usp=sharing)

## Groundwater Quality in Santa Barbara (2024)
- [Final Project ESM263 - Lecuona, Ta (Slides)](https://docs.google.com/presentation/d/1iwz47MhP-SiUuIs16FiuOwLuM3MC5gHD2D8-eT6gm1c/edit?usp=sharing)

## Modeling Beach Nourishment Costs and Volume Over Time (2025)
- [ESM 242: Beach Nourishment Mini-GP (Slides)](https://docs.google.com/presentation/d/1HwMcQWAjNNjGgERuVsKcy6CC7nkGVMAolpqc6Vem52Y/edit?usp=sharing)

## Political Communication Strategy (2024)
- [Public Campaign - Watershed Management (Slides)](https://docs.google.com/presentation/d/16fc89YyJanVhxq4aJk-b1_bRIkMO4Qw4lo92tcvM29g/edit?usp=sharing)

## Understanding the Queen Conch Fishery in the Bahamas (2022)
- [Conch Fishery in the Bahamas (Slides)](https://docs.google.com/presentation/d/10QHKkynaTDi3BB6RcPwGLXA7iDb_ZJ3ZYJ0QqzMGhZQ/edit?usp=sharing)

## Reducing Wildfire Risk via Prescribed Fires
- [American Forests, Practicum #4, ESM 228 (Slides)](https://docs.google.com/presentation/d/1MFcSjPUVh9X8UHq43RAdNRkr455-ejd0vQlLnI2gDZE/edit?usp=sharing)